### ISSUE TITLE
No API detected

### ISSUE THREAD

**Issue by olitreadwell** [BenjaminOddou/alfred-emoji-wine#1]
My attempts to use this result in 'No API detected'

I have tried to run the suggested action by pressing enter. 

I have also run 'harvest'

Same issue continues to occur.

**Comment by BenjaminOddou** [comment]
Hello @olitreadwell, it seems the api is not built correctly. First, delete any file in `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.emoji_wine`. Then check that you have python 3.8 or above with `python --version` and ensure you have `pillow` with `which pillow` command in your terminal. If everything seems ok, would you mind opening the Alfred debugger and telling me what's the error message ? See [here](https://www.alfredapp.com/help/workflows/advanced/debugger/) on how to use it.

**Comment by BenjaminOddou** [comment]
@olitreadwell could you try using the latest release [v1.2.2](https://github.com/BenjaminOddou/alfred-emoji-wine/releases/tag/v1.2.2) ?

**Comment by vitorgalvao** [comment]
@BenjaminOddou You’re hardcoding `pillow_dir = '/usr/local/Cellar/pillow'` which will not work on Apple Silicon Macs, because Homebrew installs to `/opt/homebrew` there.

**Comment by stan-voo** [comment]
Installing dependencies has worked for me.

**Comment by BenjaminOddou** [comment]
> @BenjaminOddou You’re hardcoding `pillow_dir = '/usr/local/Cellar/pillow'` which will not work on Apple Silicon Macs, because Homebrew installs to `/opt/homebrew` there.

Do you have the full path of pillow dependency installed via homebrew with apple silicon chips ? I'll recode that part. Don't hesitate to make a pull request

**Comment by vitorgalvao** [comment]
It follows the same pattern: `/opt/homebrew/Cellar/pillow`. But is it worth doing at all? Seems like this was just a matter of missing dependencies. Alfred [already includes both Homebrew paths](https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/) so no need to link to the specific Python version or anything.

A suggestion is to instead try to run a simple pillow command and on failure tell the user they may be missing the dependency. You can open `alfredpreferences://navigateto/workflows>resolvedependencies` to send people directly to the dependencies manager.

**Comment by BenjaminOddou** [comment]
It seems that when running the python script, the pillow dependency installed with homebrew is not included in pythonpath by default.

**Comment by vitorgalvao** [comment]
Check the Dependencies Manager. Does Python ask to be installed? Homebrew separates python per version and that matters regarding which version Pillow is built against.

**Comment by BenjaminOddou** [comment]
I have python 3.11 installed and my pillow version is located here `/usr/local/Cellar/pillow/10.0.0`.

```shell
==> pillow: stable 10.0.0 (bottled), HEAD
Friendly PIL fork (Python Imaging Library)
https://python-pillow.org
/usr/local/Cellar/pillow/10.0.0 (243 files, 4.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-07-17 at 21:23:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pillow.rb
License: HPND
==> Dependencies
Build: pkg-config ✔, python@3.10 ✔, python@3.11 ✔
Required: jpeg-turbo ✔, libimagequant ✔, libraqm ✔, libtiff ✔, libxcb ✔, little-cms2 ✔, openjpeg ✔, tcl-tk ✔, webp ✔
```

```python
print(sys.path)
['~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.8B870FAD-33DF-4867-AF18-0FE255A691FF', '/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python311.zip', '/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11', '/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages']
```

The problem is that `/usr/local/Cellar/<Homebrew package>/nested_folder/` link is not included in the path. Normally I would include a `./lib` folder path if I bundle the library but this time it's a bit trickier.
