### ISSUE TITLE
NO API detected

### ISSUE THREAD

**Issue by ljcliu** [BenjaminOddou/alfred-emoji-wine#10]
![Screenshot 2024-04-03 at 12 34 16 AM](https://github.com/BenjaminOddou/alfred-emoji-wine/assets/44239616/980171b0-2e42-49bc-8704-5a536084d6ed)

Installed python 3.12.2
pillow/10.3.0
apple m2 pro

**Comment by BenjaminOddou** [comment]
Hello @ljcliu it's normal if that's the first time you are using the workflow. The first thing you need to do is to build your local API. To do so, simply press enter after triggering `wine` or refresh the API after triggering `harvest` command. Wait the success notification (it should take 30sec - 1mn max).

**Comment by ljcliu** [comment]
I waited for 10 mins, still no API detected

**Comment by BenjaminOddou** [comment]
@ljcliu could you check the logs under `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.emoji_wine` ? You can also provide Alfred logs if you want

**Comment by ljcliu** [comment]
2024-04-03 18:07:54,595 - ERROR - cannot import name 'Image' from 'PIL' (unknown location)

**Comment by ljcliu** [comment]
> @ljcliu could you check the logs under `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.emoji_wine` ? You can also provide Alfred logs if you want

2024-04-03 18:07:54,595 - ERROR - cannot import name 'Image' from 'PIL' (unknown location)

**Comment by BenjaminOddou** [comment]
How did you install pillow ? It seems that the script couldn't import the package. Pillow should be under `/Users/usr/anaconda3/envs/work/lib/python3.12/site-packages` which looks like you're using a virtual environment. Did you activate it properly ? You can verify it with `(your_environment_name) $`. Could you try to check that you're using python 3.12 : `python --version` ?
