### ISSUE TITLE
Feature: skin tone selection

### ISSUE THREAD

**Issue by gabrielwhite** [BenjaminOddou/alfred-emoji-wine#11]
Hi - it would be nice to be able to set a skin tone in the configuration so that I can avoid seeing many results of the same emoji in different skin tones (e.g. search for "waving"). Thank you!

**Comment by BenjaminOddou** [comment]
Hello @gabrielwhite, this feature was added in the latest release  [v1.5.0](https://github.com/BenjaminOddou/alfred-emoji-wine/releases/tag/v1.5.0) 🎉 !

**Comment by gabrielwhite** [comment]
🙏
