### ISSUE TITLE
The size of emoji's icon is too small

### ISSUE THREAD

**Issue by pokk** [BenjaminOddou/alfred-emoji-wine#2]
Thank you so much for the awesome extension.
Just a quick question, is it possible to make the icon bigger on the search bar?

<img width="592" alt="2023-09-03-3-21-18" src="https://github.com/BenjaminOddou/alfred-emoji-wine/assets/5198104/05531797-b2e7-4b84-ae81-338af30346d3">

Like other plugins

<img width="395" alt="2023-09-03-3-21-55" src="https://github.com/BenjaminOddou/alfred-emoji-wine/assets/5198104/adaced07-24fb-4c8a-877b-44c6336a9634">

**Comment by BenjaminOddou** [comment]
Hello @pokk

This is because pillow library generates icons on the fly without any margin trimming. I will think of a system to let you control size of the icon. I personally prefer it smaller than other plugins but I totally understand you prefer bigger icons.

**Comment by BenjaminOddou** [comment]
@pokk should be fix with [v1.2.4](https://github.com/BenjaminOddou/alfred-emoji-wine/releases/tag/v1.2.4). Change the padding to a small value, and refresh your API.

**Comment by pokk** [comment]
@BenjaminOddou 
Thank you very much for your quick response. This is functioning flawlessly and is precisely what I needed!
