### ISSUE TITLE
update documentation to include pillow installation

### ISSUE THREAD

**Issue by joshuawagner** [BenjaminOddou/alfred-emoji-wine#3]
Hi, and thanks for such a cool workflow! I just wanted to say that I just about abandoned the installation process after I clicked "Install in Alfred" (from the Alfred Gallery) and it didn't work. I noticed that the page said that pillow was required so I clicked on the "Alfred can help [manage Homebrew dependencies](https://www.alfredapp.com/help/kb/dependencies/) once the workflow is installed" link and followed the instructions. You may want to include this in your instructions.

**Comment by BenjaminOddou** [comment]
Hey @joshuawagner thanks for reaching out. It's under the `Setup the workflow` section in the docs but I may include it in the prerequisite as well in order to make it clearer for new users.

**Comment by BenjaminOddou** [comment]
Close as updated [here](https://github.com/BenjaminOddou/alfred-emoji-wine/commit/29e758e8c607deb022fc2dfc2ec073a0bc36dd54).
