### ISSUE TITLE
No API Detected and Error Message: Check Internet Connexion

### ISSUE THREAD

**Issue by tujuhtigatujuh** [BenjaminOddou/alfred-emoji-wine#4]
I encounter an error indicating a problem with the internet connection or prompting me to create an issue on GitHub when attempting to open the application.

**Comment by BenjaminOddou** [comment]
Hey @tujuhtigatujuh thanks for the feedback. Did you install [pillow](https://github.com/BenjaminOddou/alfred-emoji-wine#-setup-the-workflow) library along with the workflow ?

**Comment by tujuhtigatujuh** [comment]
Yup, I installed pillow.

Sent via Superhuman iOS ( ***@***.*** )

**Comment by tujuhtigatujuh** [comment]
Delete and re-install. Work just fine now.

**Comment by BenjaminOddou** [comment]
Nice. Just want to let you know that [v1.2.6](https://github.com/BenjaminOddou/alfred-emoji-wine/releases/tag/v1.2.6) now embedded a logging system that allows you to debug more rapidly. You'll be able to see the `emoji_wine.log` here : `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.emoji_wine`
