### ISSUE TITLE
Feature request: immediate pasting of selected emoji

### ISSUE THREAD

**Issue by gabrielwhite** [BenjaminOddou/alfred-emoji-wine#6]
Thanks for making emoji search so much easier!

One thing that would be great if you could add an option to the workflow configuration along the lines of:

( ) Copy selected emoji to clipboard
( ) Paste selected emoji immediately

I generally summon this workflow when I'm editing and I want the emoji the land directly in the editor rather than in the clipboard.

**Comment by BenjaminOddou** [comment]
Hello @gabrielwhite thanks for reaching out ! I think you may want to use <kbd>⌘</kbd><kbd>⏎</kbd>, see this [section](https://github.com/BenjaminOddou/alfred-emoji-wine#workflow-actions) of the docs.

**Comment by gabrielwhite** [comment]
🙏

**Comment by gabrielwhite** [comment]
🙏
